I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 93, in script
    K "THIS PLACE IS SO DISRESPECTFUL!"
Exception: Sayer 'K' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 93, in script
    K "THIS PLACE IS SO DISRESPECTFUL!"
  File "C:\Users\y29_113063\OneDrive - Tara\Desktop\Personal\renpy-8.3.7-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "C:\Users\y29_113063\OneDrive - Tara\Desktop\Personal\renpy-8.3.7-sdk\renpy\ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\y29_113063\OneDrive - Tara\Desktop\Personal\renpy-8.3.7-sdk\renpy\ast.py", line 472, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'K' is not defined.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
frog restaurant 1.0
Fri Aug 29 21:24:20 2025
